package pojo;
// Generated 25 nov 2022 12:11:08 by Hibernate Tools 5.5.9.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Animales generated by hbm2java
 */

@Entity
@Table(name="animales")
public class Animal implements java.io.Serializable {
	@Id
	@Column(name="id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Column(name="nombre", unique=true, nullable=false, length =50)
	private String nombre;
	

	@Column(name="habitad", nullable = false, length = 40)
	private String habitad;
	

	@Column(name="pesoAprox", nullable=false, length = 10, precision = 2)
	private BigDecimal pesoAprox;

	public Animal() {
		
	}

	public Animal(String nombre, String habitad, BigDecimal pesoAprox) {
		this.nombre = nombre;
		this.habitad = habitad;
		this.pesoAprox = pesoAprox;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getHabitad() {
		return this.habitad;
	}

	public void setHabitad(String habitad) {
		this.habitad = habitad;
	}

	public BigDecimal getPesoAprox() {
		return this.pesoAprox;
	}

	public void setPesoAprox(BigDecimal pesoAprox) {
		this.pesoAprox = pesoAprox;
	}

}
