package pojo;
// Generated 2 dic 2022 14:25:06 by Hibernate Tools 5.5.9.Final

/**
 * Zoologicos generated by hbm2java
 */
public class Zoologicos implements java.io.Serializable {

	private int id;
	private String nombre;
	private String ciudad;
	private int anoFundacion;

	public Zoologicos() {
	}

	public Zoologicos(int id, String nombre, String ciudad, int anoFundacion) {
		this.id = id;
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.anoFundacion = anoFundacion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public int getAnoFundacion() {
		return this.anoFundacion;
	}

	public void setAnoFundacion(int anoFundacion) {
		this.anoFundacion = anoFundacion;
	}

}
